### ISSUE TITLE
RSS Feed automatically merging if you already have This American Life on your podcast app

### ISSUE THREAD

**Issue by IQAndreas** [awkspace/this-american-scraper#1]
If you're already subscribed to This American Life in your podcast app (tested in Google Podcasts and PodcastAddict), trying to subscribe to this RSS feed will give you an error message along the lines of "Already subscribed to this podcast".

I'm not sure exactly which identifier it's using (likely the `title` or `link`), but changing either of these might fix it.

I'd like to suggest something like `This American Life (Archive)`, and maybe a modified icon so it's easy to tell the difference between the two in the player.

**Comment by awkspace** [comment]
This feed incorporates all of the episodes from the truncated one, so you may not need to be subscribed to both. However, in the podcatcher I use (Pocket Casts), I can subscribe to both without issue.

I don't use Google Podcasts or PodcastAddict and I am unwilling to install every podcast app out there to test adding both feeds. Unfortunately, there is no standard for feed deduplication. Each app has their own, often unpublished, method for doing so.

That's not to say I don't want to solve the problem for users of other apps, just that I don't know how. If you find something specific that I can do to modify the feed that will get this working in your preferred podcatcher, please re-open this issue. If you want to play around with it yourself, you could fork this repository and modify the data in feed.xml until it no longer registers as a dupe.

By the way, the `title` tag already differs: it is "This American Life Archive" vs. "This American Life" for the truncated feed.
